### ISSUE TITLE
Text on Fun page not readable

### ISSUE THREAD

**Issue by Pohli** [Rikujolla/harbour-math-teacher#1]
The describing text on the Fun page is partially covered by the pictures from the next row.
![Screenshot_20191018_001](https://user-images.githubusercontent.com/26346589/67111049-6caabb80-f1d4-11e9-8c18-146b2eec0946.png)
Jolla Phone with SFOS 3.0.1.11 and Math Teacher 0.0.6

**Comment by Rikujolla** [comment]
Thanks for reporting. I'll fix in next version hopefully next week.

**Comment by Rikujolla** [comment]
Fixed in version 0.0.7

**Comment by Pohli** [comment]
Thanks, it looks good now.
