### ISSUE TITLE
Add progress indicator

### ISSUE THREAD

**Issue by Pohli** [Rikujolla/harbour-math-teacher#3]
Can you add some kind of progress indicator which shows how far or close from the fun page one is? It doesn't have to be an exact number indicating how many math problems are left, a progress bar or something similar would also do it. I think it would be more motivating that way. Right now it feels like solving problems endlessly.

**Comment by Rikujolla** [comment]
Thanks for your comment! I have to look at that in the next version.

**Comment by Rikujolla** [comment]
Fixed in the version 0.0.8
